dataset_params:
  im_path: 'data/coco_pose/images'
  pose_path: 'data/coco_pose/poses'
  im_channels: 3
  im_size: 256
  name: 'coco_pose'

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.0015
  beta_end: 0.0195

ldm_params:
  hint_channels: 3
  down_channels: [256, 384, 512, 768]
  mid_channels: [768, 512]
  down_sample: [True, True, True]
  attn_down: [False, True, True]    
  time_emb_dim: 512
  norm_channels: 32
  # num_heads: 16                     # for LDM
  num_heads: 8                        # for LDM + controlnet
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  conv_out_channels: 128

autoencoder_params:
  z_channels: 4
  codebook_size: 8192
  down_channels: [128, 256, 384]
  mid_channels: [384]
  down_sample: [True, True]
  attn_down: [False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2

train_params:
  seed: 1111
  task_name: 'coco_pose'

  # -------- Autoencoder --------
  autoencoder_batch_size: 1
  autoencoder_epochs: 5
  autoencoder_lr: 0.00001
  autoencoder_acc_steps: 4
  autoencoder_img_save_steps: 64

  disc_start: 7500
  disc_weight: 0.5
  perceptual_weight: 1
  kl_weight: 0.000005

  save_latents: True
  vae_latent_dir_name: 'vae_latents'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'

  # -------- LDM  --------
  ldm_batch_size: 1
  ldm_epochs: 50
  ldm_lr: 0.000025
  ldm_lr_steps: [50, 100, 150]
  ldm_ckpt_name: 'ldm_ckpt.pth'

  # -------- ControlNet --------
  controlnet_lr: 0.00001
  controlnet_ckpt_name: controlnet_ckpt.pth
  controlnet_lr_steps: [10, 20, 30]
  ldm_batch_size: 1
  ldm_epochs: 30


  # -------- Visualization  --------
  num_samples: 8
  num_grid_rows: 4


